# Generated by Django 4.1.7 on 2023-04-01 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetos',
            name='nome',
        ),
        migrations.AddField(
            model_name='clientes',
            name='area',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
